version: "3.9"
services:
  mysql:
    container_name: mysql
#    image: mysql:latest
    build: mysql
    env_file: mysql.env
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  php:
    container_name: php
    build: .
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html/api
      - ./apache2/sites-available:/etc/apache2/sites-available
    depends_on:
      - mysql
      - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: root
    volumes:
      - data_redis:/data
volumes:
  dbdata:
  data_redis:
