FROM mysql:latest

# Copy the shell script to the container
COPY create_db.sh /docker-entrypoint-initdb.d/

# Grant executable permission to the shell script
RUN chmod +x /docker-entrypoint-initdb.d/create_db.sh